# Generated by Django 4.2.4 on 2023-10-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cat_dec', models.CharField(blank=True, max_length=100, null=True)),
                ('cat_quan', models.CharField(blank=True, max_length=100, null=True)),
                ('cat_price', models.IntegerField(blank=True, null=True)),
                ('cat_image', models.ImageField(blank=True, null=True, upload_to='category')),
            ],
        ),
    ]
