# Generated by Django 4.2.4 on 2023-10-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0004_rename_cat_img_catdata_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catdata',
            old_name='image',
            new_name='images',
        ),
    ]
