# Generated by Django 4.2.4 on 2023-10-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0005_rename_image_catdata_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='catdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cate_dec', models.CharField(blank=True, max_length=100, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='cat')),
            ],
        ),
    ]
