# Generated by Django 4.2.4 on 2023-10-12 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0006_catdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catdetail',
            old_name='cate_dec',
            new_name='cate_de',
        ),
        migrations.RenameField(
            model_name='catdetail',
            old_name='cate_name',
            new_name='cate_nam',
        ),
        migrations.RenameField(
            model_name='catdetail',
            old_name='images',
            new_name='image',
        ),
    ]
