# Generated by Django 4.2.4 on 2023-10-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logindb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(blank=True, max_length=100, null=True)),
                ('s_user', models.CharField(blank=True, max_length=100, null=True)),
                ('s_pass', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
