# Generated by Django 4.2.4 on 2023-10-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(blank=True, max_length=100, null=True)),
                ('c_email', models.CharField(blank=True, max_length=100, null=True)),
                ('c_subject', models.CharField(blank=True, max_length=100, null=True)),
                ('c_message', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
