# Generated by Django 4.2.4 on 2023-10-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0002_contactdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ca_price', models.CharField(blank=True, max_length=100, null=True)),
                ('ca_qty', models.CharField(blank=True, max_length=100, null=True)),
                ('ca_total', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
